# -*- coding: utf-8 -*-
#Created on 2015��3��24��

#@author: etbcffg

#file ConnectionConfig path
CONNECTION_CONFIG = 'ConnectionConfig.ini'            
CONNECTION_CONFIG_OPTION = 'addr'                                    
DEVICE_NAME_RRU = 'RRU'
DEVICE_NAME_SIGNALANALYZER = 'SIGNALANALYZER'
DEVICE_NAME_SIGNALGENERATOR = 'SIGNALGENERATOR'
DEVICE_NAME_RFBOX = 'RFBOX'
DEVICE_NAME_RuMaster = 'RuMaster'
DEVICE_NAME_INTERFERENCE_SIGNAL_1 = 'INTERFERENCE_SIGNAL_1'
DEVICE_NAME_INTERFERENCE_SIGNAL_2 = 'INTERFERENCE_SIGNAL_2'

RRU_COMMAND_CONFIG_PATH = 'RRU_Commands.ini'
RRU_COMMANDS_SECTIONLABLE = ("[","]")

#pyvisa timeout
OPERATION_TIMEOUT = 1

WEB_TOOL_NAME_RRU = 'RRU'
WEB_TOOL_NAME_SIGNALANALYZER = 'SA'
WEB_TOOL_NAME_SIGNALGENERATOR = 'SG'
WEB_TOOL_NAME_RFBOX = 'RFBOX'
WEB_TOOL_NAME_RuMaster = 'RuMaster'

WEB_TOOL_USERS = ['zxiao','wminjuan','wziguang']
LOCAL_SOCKET_SERVER_PORT = 8111